import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import FooterComponent from "./FooterComponent.js"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Refresh Church",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
        <FooterComponent/>
      </body>
    </html>
  );
}
