import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import FooterComponent from "./FooterComponent.js"
import { Analytics } from "@vercel/analytics/react"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Refresh Church",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/r-favicon.svg" type="image/svg+xml" />
      </head>
      <body className={inter.className}>
        <Navbar />
        {children}
        <FooterComponent />
        <Analytics />
      </body>
    </html>
  );
}
