"use client"

export default function Beliefs() {
  const beliefs = [
    { title: "Holy Bible", blurb: "The Holy Bible, and only the Bible, is the authoritative Word of God. It alone is the final authority in determining all doctrinal truths. In its original writing, it is inspired, infallible and inerrant (II Timothy 3:16; II Peter 1:20-21; Proverbs 30:5; Romans 16:25-26)." },
    { title: "The Trinity", blurb: "There is one God, eternally existent in three persons: Father, Son and Holy Spirit. These three are coequal and co-eternal (I John 5:7; Genesis 1:26; Matthew 3:16-17, 28:19; Luke 1:35; Isaiah 9:6; Hebrews 3:7-11)." },
    { title: "Jesus Christ", blurb: "Jesus Christ is God the Son, the second person of the Trinity. On earth, Jesus was 100% God and 100% man. He is the only man ever to have lived a sinless life. He was born of a virgin, lived a sinless life, performed miracles, died on the cross for mankind and thus, atoned for our sins through the shedding of His blood. He rose from the dead on the third day according to the Scriptures, ascended to the right hand of the Father, and will return again in power and glory. (John 1:1,14, 20:28; I Timothy 3:16; Isaiah 9:6; Philippians 2:5-6; I Timothy 2:5)." },
    { title: "Virgin Birth", blurb: "Jesus Christ was conceived by God the Father, through the Holy Spirit (the third person of the Trinity) in the virgin Mary’s womb; therefore, He is the Son of God (Matthew 1:18, 25; Luke 1:35; Isaiah 7:14; Luke 1:27-35)." },
    { title: "Regeneration", blurb:  "For anyone to know God, regeneration by the Holy Spirit is absolutely essential (John 6:44, 65; Matthew 19:28; Titus 3:5)." },
    { title: "Redemption", blurb:  "Man was created good and upright, but by voluntary transgression he fell; his only hope of redemption is in Jesus Christ, the Son of God (Gen. 1:26-31, 3:1-7; Romans 5:12-21)." },
    { title: "Repentance", blurb:  "Repentance is the commitment to turn away from sin in every area of our lives and to follow Christ, which allows us to receive His redemption and to be regenerated by the Holy Spirit. Thus, through repentance we receive forgiveness of sins and appropriate salvation (Acts 2:21, 3:19; I John 1:9)." },
    { title: "Salvation", blurb:  "We are saved by grace through faith in Jesus Christ: His death, burial, and resurrection. Salvation is a gift from God, not a result of our good works or of any human efforts (Ephesians 2:8-9; Galatians 2:16, 3:8; Titus 3:5; Romans 10:9-10; Acts 16:31; Hebrews 9:22)." },
    { title: "Jesus' Blood", blurb:  "The Blood that Jesus Christ shed on the Cross of Calvary was sinless and is 100% sufficient to cleanse mankind of all sin. Jesus allowed Himself to be punished for both our sinfulness and our sins, enabling all those who believe to be free from the penalty of sin, which is death (I John 1:7; Revelation 1:5, 5:9; Colossians 1:20; Romans 3:10-12, 23, 5:9; John 1:29)." },
    { title: "Sanctification", blurb:  "Sanctification is the ongoing process of yielding to God’s Word and His Spirit in order to complete the development of Christ’s character in us. It is through the present ministry of the Holy Spirit and the Word of God that the Christian is enabled to live a Godly life (I Thessalonians 4:3, 5:23; II Corinthians 3:18, 6:14-18, II Thessalonians 2:1-3, Romans 8:29, 12:1-2, Hebrews 2:11)." },
    { title: "Gifts of the Holy Spirit", blurb:  "The Holy Spirit is manifested through a variety of spiritual gifts to build and sanctify the church, demonstrate the validity of the resurrection, and confirm the power of the Gospel. The Bible’s lists of these gifts are not necessarily exhaustive, and the gifts may occur in various combinations. All believers are commanded to earnestly desire the manifestation of the gifts in their lives. These gifts always operate in harmony with the Scriptures and should never be used in violation of Biblical parameters. (Hebrews 2:4; Romans 1:11, 12 :4-8; Ephesians 4:16; I Timothy 4:14; II Timothy 1:6-7; I Corinthians 12:1-31, 14:1-40; I Peter 4:10)." },
    { title: "Jesus Christ indwells all believers", blurb:  "Christians are people who have invited the Lord Jesus Christ to come and live inside them by His Holy Spirit. They relinquish the authority of their lives over to him thus making Jesus the Lord of their life as well as Savior. They put their trust in what Jesus accomplished for them when He died, was buried, and rose again from the dead (John 1:12; John 14:17, 23; John 15:4; Romans 8:11; Revelation 3:20)." },
    { title: "Resurrection", blurb:  "Jesus Christ was physically resurrected from the dead in a glorified body three days after His death on the cross. In addition, both the saved and the lost will be resurrected; they that are saved to the resurrection of life and they that are lost to the resurrection of eternal damnation (Luke 24:16, 36, 39; John 2:19-21, 20:26-28, 21:4; Acts 24:15; I Corinthians 15:42, 44; Philippians 1:21-23, 3:21)." },
    { title: "The Church", blurb:  "The church is the Body of Christ, the habitation of God through the Spirit, with divine appointments for the fulfillment of Jesus’ Great Commission. Every person who is born of the Spirit is an integral part of the church as a member of the body of believers. There is a spiritual unity of all believers in our Lord Jesus Christ. (Ephesians 1:22, 2:19-22; Hebrews 12:23; John 17:11, 20-23)." },
  ];

  return (
    <div className="container mx-auto px-8 sm:px-36 py-12">
      {/* Page Title */}
      <h2 className="text-4xl font-bold text-gray-900 tracking-tighter sm:text-4xl md:text-5xl mb-12">Our Beliefs</h2>

      {/* Hero Blurb */}
      <div className="bg-white shadow-lg rounded-2xl p-8 mb-12 text-center">
        <p className="text-lg text-gray-700">
          Our goal as a church is to create an environment where you can come and be refreshed by all that God is doing. We believe God wants you to experience greater life, greater relationships, and a greater sense of purpose! See below how we view God, Jesus, the Bible, man, and many significant aspects of our faith. Firmly rooted in Scripture, the beliefs of Refresh guide our decisions as a church.
        </p>
      </div>

      {/* Church Slogan */}
      <div className="text-center mb-12">
        <h3 className="text-2xl font-bold text-primary lowercase">every person refreshed. every purpose discovered.</h3>
      </div>

      {/* Beliefs Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-2 gap-8">
        {beliefs.map((belief, index) => (
          <div key={index} className="bg-white shadow-md rounded-2xl p-6">
            <h3 className="text-xl font-bold text-primary mb-4">{belief.title}</h3>
            <p className="text-gray-700 text-lg">{belief.blurb}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
